### ISSUE TITLE
List<UserModel> list = StoneStart.init(this)

### ISSUE THREAD

**Issue by dprado** [stone-pagamentos/sdk-android-V2#2]
o `StoneStart.init(this)` retorna uma lista de UserModel. Em quais situações mais de um ítem é retornado nesta lista?

**Comment by jgabrielfreitas** [comment]
Esse método retornará mais de um `UserModel` quando houver mais de um StoneCode ativado.
Se você ativar 3 StoneCodes, por exemplo, o `StoneStart.init(this)` irá retornar 3 itens.

```java

// supondo que tenham 3 StoneCodes ativos na sua aplicação
List<UserModel> userModelList = StoneStart.init(this);
Log.d("stonecodes", "userModelList size:" + userModelList.size()) // userModelList size: 3

```
