### ISSUE TITLE
Impressão de comprovante de transação

### ISSUE THREAD

**Issue by dprado** [stone-pagamentos/sdk-android-V2#3]
Estamos imprimindo um comprovante da transação, utilizando uma impressora própria. Como podemos obter os número da autorização e outros dados relevantes que devem ser impressos, uma vez que a transação é aprovada?

**Comment by jgabrielfreitas** [comment]
Vocês podem pegar todos os dados relevantes da transação, como identificador da mesma, data, hora, tipo da transação (crédito ou débito)... utilizando o `TransactionDAO` e informar o ID da transação que vocês querem obter os dados. Desta forma vocês poderão recuperar o `TransactionObject` e terão acesso à todos os dados necessários.
