### ISSUE TITLE
partnerDeveloper

### ISSUE THREAD

**Issue by Lukasboo** [stone-pagamentos/sdk-android-V2#6]
Preciso realizar testes, então estou  tentando iniciar o projeto como parceiro 

Na documentação está assim
// no início do seu projeto
UserModel userModel = StoneStart.init(SUA_ACTIVITY_AQUI);

// diz que é um desenvolvedor com essas duas linhas de código
Partner partnerDeveloper = new Partner(userModel);
GlobalInformations.sessionApplication.setUserModel(partnerDeveloper);

mas o exemplo do sdk, o UserModel está assim
List<UserModel> user = StoneStart.init(this);

O método setUserModel de sessionApplication não existe, o método que existe na sessionApplication é o setUserModelList, quando é criado a instância de Partner, o parâmetro pedido é UserModel, até aí tudo bem, pois é só colocar o index zero da "List<UserModel> user",  mas a sessionApplication.setUserModelList(); pede como parâmetro uma List<UserModel>, aí não da pra usar o Partner pois ele retorna o UserModel e não o List<UserModel>, se faço cast do Partner para    
"(List<UserModel>) partner" da um erro que não pode dar cast em partner, como posso resolver isso?

**Comment by jgabrielfreitas** [comment]
Olá @Lukasboo ,
Bom, pra habilitar o modo de desenvolvedor você vai ter que chamar o método `GlobalInformations.developerMode()` após o `StoneStart.init(this)` retornar uma lista válida de StoneCodes ativos. 

**Exemplo:**
```java
// pega a lista de lojistas ativos
List<UserModel> userList = StoneStart.init(this);

// certifica que há lojistas retornados do método init 
if (userList.size() > 0) {

       // habilita o modo dev
       GlobalInformations.developerMode();

       // continua o fluxo da sua aplicação 
}

```

Depois disso feito, a SDK irá apontar para o ambiente de homologação da Stone

**Comment by Lukasboo** [comment]
Olá João,


eu coloquei do modo que você me orientou,

depois eu criei uma variável para testes e ela me retorna false,

após instalar o app, essa é a segunda vez que estou rodando ele.

Se eu entendi bem, quando o userCode é 1, é que está no modo desenvolvedor,

olhei os dados do user e o userCode continua sendo ZERO mesmo após passar pelo GlobalInformation.developerMode()


List<UserModel> user = StoneStart.init(this);
boolean teste = GlobalInformations.isDeveloper(user.get(0));
// se retornar nulo, voce provavelmente nao ativou a SDK
// ou as informacoes da Stone SDK foram excluidas
if (user == null) {
    // habilita o modo dev
    GlobalInformations.developerMode();
    List<String> stoneCodeList = new ArrayList<>();

Att


Lucas


________________________________
De: João Gabriel de Freitas <notifications@github.com>
Enviado: terça-feira, 18 de outubro de 2016 11:35
Para: stone-pagamentos/sdk-android-V2
Cc: Lucas Daniel Pedroso; Mention
Assunto: Re: [stone-pagamentos/sdk-android-V2] partnerDeveloper (#6)


Olá @Lukasboo<https://github.com/Lukasboo> ,
Bom, pra habilitar o modo de desenvolvedor você vai ter que chamar o método GlobalInformations.developerMode() após o StoneStart.init(this) retornar uma lista válida de StoneCodes ativos.

Exemplo:

// pega a lista de lojistas ativos
List<UserModel> userList = StoneStart.init(this);

// certifica que há lojistas retornados do método init
if (userList.size() > 0) {

       // habilita o modo dev
       GlobalInformations.developerMode();

       // continua o fluxo da sua aplicação
}


Depois disso feito, a SDK irá apontar para o ambiente de homologação da Stone

-

**Comment by jgabrielfreitas** [comment]
Então, o init só retornará a quantidade de lojistas que você passou (se você ativar 2 StoneCodes, o init irá retornar 2), apenas isso.
O modo desenvolvedor é habilitado só de chamar o método `.developerMode()`, só de fazer isso você já vai para o ambiente de homologação, não disponibilizamos uma forma de saber se está em modo de desenvolvimento ou não, é só chamar o método ou não. Entende?

Pode estar retornando zero porque você não deve ter ativado a SDK ainda. Você já chamou o `ActiveApplicationProvider` ?

**Exemplo**
```java

public void activeApplication() {

  // Este deve ser, obrigatoriamente, o primeiro método a ser chamado. É um método que trabalha com sessão.
  List<UserModel> listOfUser = StoneStart.init(SUA_MAIN_ACTIVITY_AQUI);

  // Se retornar nulo, você provavelmente não ativou o SDK ou as informações do Stone SDK foram excluídos.
  if (listOfUser == null) {
      List<String> stoneCodeToActiveList = new ArrayList<String>();
      stoneCodeToActiveList.add(STONE_PRODUCT_KEY);

      ActiveApplicationProvider activeApplicationProvider = new ActiveApplicationProvider(SUA_MAIN_ACTIVITY_AQUI, stoneCodeToActiveList); // Você deve colocar seu StoneCode aqui.
      activeApplicationProvider.setDialogMessage("Ativando o aplicativo");
      activeApplicationProvider.setDialogTitle("Aguarde");
      activeApplicationProvider.setWorkInBackground(false); // Informa se este provider irá rodar em background ou não.
      activeApplicationProvider.setConnectionCallback(new StoneCallbackInterface() {
         /* Sempre que utilizar um provider, instancie esta interface.
          * Ela irá lhe informar se o provider foi executado com sucesso ou não. */

         // Método chamado se for executado sem erros
         public void onSuccess() {
           Toast.makeText(getApplicationContext(), "Ativado com sucesso", LENGTH_SHORT).show();
           continueApplication();
         }

         // Método chamado caso ocorra alguma exceção
         public void onError() {
           Toast.makeText(getApplicationContext(), "Erro na ativação do aplicativo", LENGTH_SHORT).show();
           // Chame o método abaixo para verificar a lista de erros. Para mais detalhes, leia a documentação.
           activeApplicationProvider.getListOfErrors();
         }
      });
      activeApplicationProvider.execute();
  } else {
      // Caso já tenha as informações do SDK e chamado o ActiveApplicationProvider anteriormente, sua aplicação poderá seguir o fluxo normal.
      continueApplication();
  }
}

private void continueApplication() {
     // habilita o modo dev
     GlobalInformations.developerMode();

     // continua a sua aplicação . . .
}
```

**Comment by Lukasboo** [comment]
Sim, está ativando corretamente, na verdade estou usando o sdkDemo, primeiro vou fazer uns testes com o sdkDemo, quando estiver tudo ok eu faço a integração com meu app, vou continuar testando aqui,


Obrigado pela ajuda


Att


Lucas



________________________________
De: João Gabriel de Freitas <notifications@github.com>
Enviado: terça-feira, 18 de outubro de 2016 15:04
Para: stone-pagamentos/sdk-android-V2
Cc: Lucas Daniel Pedroso; Mention
Assunto: Re: [stone-pagamentos/sdk-android-V2] partnerDeveloper (#6)


Então, o init só retornará a quantidade de lojistas que você passou (se você ativar 2 StoneCodes, o init irá retornar 2), apenas isso.
O modo desenvolvedor é habilitado só de chamar o método .developerMode(), só de fazer isso você já vai para o ambiente de homologação, não disponibilizamos uma forma de saber se está em modo de desenvolvimento ou não, é só chamar o método ou não. Entende?

Pode estar retornando zero porque você não deve ter ativado a SDK ainda. Você já chamou o ActiveApplicationProvider ?

Exemplo

public void activeApplication() {

  // Este deve ser, obrigatoriamente, o primeiro método a ser chamado. É um método que trabalha com sessão.
  List<UserModel> listOfUser = StoneStart.init(SUA_MAIN_ACTIVITY_AQUI);

  // Se retornar nulo, você provavelmente não ativou o SDK ou as informações do Stone SDK foram excluídos.
  if (listOfUser == null) {
      List<String> stoneCodeToActiveList = new ArrayList<String>();
      stoneCodeToActiveList.add(STONE_PRODUCT_KEY);

      ActiveApplicationProvider activeApplicationProvider = new ActiveApplicationProvider(SUA_MAIN_ACTIVITY_AQUI, stoneCodeToActiveList); // Você deve colocar seu StoneCode aqui.
      activeApplicationProvider.setDialogMessage("Ativando o aplicativo");
      activeApplicationProvider.setDialogTitle("Aguarde");
      activeApplicationProvider.setWorkInBackground(false); // Informa se este provider irá rodar em background ou não.
      activeApplicationProvider.setConnectionCallback(new StoneCallbackInterface() {
         /* Sempre que utilizar um provider, instancie esta interface.
          * Ela irá lhe informar se o provider foi executado com sucesso ou não. */

         // Método chamado se for executado sem erros
         public void onSuccess() {
           Toast.makeText(getApplicationContext(), "Ativado com sucesso", LENGTH_SHORT).show();
           continueApplication();
         }

         // Método chamado caso ocorra alguma exceção
         public void onError() {
           Toast.makeText(getApplicationContext(), "Erro na ativação do aplicativo", LENGTH_SHORT).show();
           // Chame o método abaixo para verificar a lista de erros. Para mais detalhes, leia a documentação.
           activeApplicationProvider.getListOfErrors();
         }
      });
      activeApplicationProvider.execute();
  } else {
      // Caso já tenha as informações do SDK e chamado o ActiveApplicationProvider anteriormente, sua aplicação poderá seguir o fluxo normal.
      continueApplication();
  }
}

private void continueApplication() {
     // habilita o modo dev
     GlobalInformations.developerMode();

     // continua a sua aplicação . . .
}

-
