### ISSUE TITLE
Retorno inesperado

### ISSUE THREAD

**Issue by tio-ze** [stone-pagamentos/sdk-android-V2#9]
Prezados, estou usando o sdk_stone_2.2.4.jar em developer mode e estou recebendo esse retorno intrigante:

Transaction added at base!: TransactionObject{idFromBase=0, amount='862626', requestId='null', emailSent='null', timeToPassTransaction='null', initiatorTransactionKey='null', recipientTransactionIdentification='null', cardHolderNumber='null', cardHolderName='null', date='null', time='null', aid='null', arcq='null', authorizationCode='null', iccRelatedData='null', transactionReference='null', actionCode='null', pinpadUsed='MOBI PIN 10-8000021605004229', userModelSale='null', cardBrand=null, instalmentTransaction=ONE_INSTALMENT, transactionStatus=UNKNOWN, instalmentType=null, typeOfTransactionEnum=null}
TransactionObject{idFromBase=5, amount='862626', requestId='null', emailSent='null', timeToPassTransaction='null', initiatorTransactionKey='null', recipientTransactionIdentification='null', cardHolderNumber='*************9452', cardHolderName='null', date='null', time='null', aid='null', arcq='null', authorizationCode='null', iccRelatedData='null', transactionReference='null', actionCode='null', pinpadUsed='MOBI PIN 10-8000021605004229', userModelSale='A628B35EB5D643BF99B75A09383AB184', cardBrand=null, instalmentTransaction=ONE_INSTALMENT, transactionStatus=UNKNOWN, instalmentType=null, typeOfTransactionEnum=DEBIT}
update: 1
TransactionObject{idFromBase=5, amount='862626', requestId='null', emailSent='null', timeToPassTransaction='null', initiatorTransactionKey='null', recipientTransactionIdentification='null', cardHolderNumber='*************9452', cardHolderName='CARTAO IMEDIATO           ', date='2017-03-16', time='12:08:04', aid='null', arcq='null', authorizationCode='null', iccRelatedData='null', transactionReference='null', actionCode='null', pinpadUsed='MOBI PIN 10-8000021605004229', userModelSale='A628B35EB5D643BF99B75A09383AB184', cardBrand=VISA, instalmentTransaction=ONE_INSTALMENT, transactionStatus=UNKNOWN, instalmentType=null, typeOfTransactionEnum=DEBIT}
update: 2
Bypassing SSL security checks at caller's request
I/stone_response: <?xml version="1.0" encoding="utf-8"?><Document xmlns="urn:AcceptorAuthorisationResponseV02.1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><AccptrAuthstnRspn><Hdr><MsgFctn>AUTP</MsgFctn><PrtcolVrsn>2.0</PrtcolVrsn><CreDtTm>2017-03-16T12:09:04</CreDtTm></Hdr><AuthstnRspn><Envt><MrchntId><Id>D00BF32F8A7B498A866A494BE50C9E5A</Id></MrchntId></Envt><Tx><TxId><TxDtTm>2017-03-16T12:08:04</TxDtTm><TxRef>98380dcf61294bb5be81b04c61c6cd21</TxRef></TxId><RcptTxId>17570181798213</RcptTxId><TxDtls><Ccy>986</Ccy><TtlAmt>0</TtlAmt><ICCRltdData/><AcctTp>CHCK</AcctTp></TxDtls></Tx><TxRspn><AuthstnRslt><RspnToAuthstn><Rspn>TECH</Rspn><RspnRsn>9109</RspnRsn></RspnToAuthstn><AuthstnCd>N/A</AuthstnCd><CmpltnReqrd>false</CmpltnReqrd></AuthstnRslt></TxRspn></AuthstnRspn></AccptrAuthstnRspn></Document>
TransactionObject{idFromBase=5, amount='862626', requestId='null', emailSent='null', timeToPassTransaction='1m 60s', initiatorTransactionKey='108000021605004229-707500055249449', recipientTransactionIdentification='17570181798213', cardHolderNumber='*************9452', cardHolderName='CARTAO IMEDIATO           ', date='2017-03-16', time='12:08:04', aid='null', arcq='null', authorizationCode='N/A', iccRelatedData='', transactionReference='98380dcf61294bb5be81b04c61c6cd21', actionCode='05', pinpadUsed='MOBI PIN 10-8000021605004229', userModelSale='A628B35EB5D643BF99B75A09383AB184', cardBrand=VISA, instalmentTransaction=ONE_INSTALMENT, transactionStatus=TECHNICAL_ERROR, instalmentType=None, typeOfTransactionEnum=DEBIT}
update: 3
TransactionObject{idFromBase=5, amount='862626', requestId='null', emailSent='null', timeToPassTransaction='1m 60s', initiatorTransactionKey='108000021605004229-707500055249449', recipientTransactionIdentification='17570181798213', cardHolderNumber='*************9452', cardHolderName='CARTAO IMEDIATO           ', date='2017-03-16', time='12:08:04', aid='null', arcq='null', authorizationCode='N/A', iccRelatedData='', transactionReference='98380dcf61294bb5be81b04c61c6cd21', actionCode='05', pinpadUsed='MOBI PIN 10-8000021605004229', userModelSale='A628B35EB5D643BF99B75A09383AB184', cardBrand=VISA, instalmentTransaction=ONE_INSTALMENT, transactionStatus=TECHNICAL_ERROR, instalmentType=None, typeOfTransactionEnum=DEBIT}
update: 4

Alguma sugestão?

**Comment by jgabrielfreitas** [comment]
@tio-ze nós liberamos alguns updates da SDK. 
Atualmente está na **2.1.10**. Pode testar nela e ver se o erro continua?

**Comment by tio-ze** [comment]
Oi @jgabrielfreitas. Obrigado pela resposta rápida. Estou um pouco confuso com uma coisa: no meu projeto, estou usando a 2.2.4. Você está me sugerindo fazer um downgrade pra 2.1.10?
Abs,
@tio-ze

**Comment by jgabrielfreitas** [comment]
Desculpa @tio-ze , é a **2.2.10**!
Pode ir acompanhando as versões e o changelog [aqui](https://github.com/stone-pagamentos/sdk-android-V2/blob/master/JARs/changelog.md)

**Comment by tio-ze** [comment]
Olá @jgabrielfreitas ,

ao mudar a versão, o aponta que não existem mais diversos pacotes. Por exemplo:
error: package stone.application.enums does not exist.
E alguns outros além desses. Procede?

**Comment by jgabrielfreitas** [comment]
nós temos uma demo com a mesma versão, dá uma olhada: https://github.com/stone-pagamentos/demo-sdk-android

**Comment by jgabrielfreitas** [comment]
funcionou @tio-ze ?

**Comment by tio-ze** [comment]
Bom dia @jgabrielfreitas. Ainda não baixei a demo pra ver. Mas estamos analisando no projeto se vale fazer um refactor de 80 classes, ou ficar sem ambiente de homologação.....

**Comment by tio-ze** [comment]
Olá @jgabrielfreitas. Baixei a demo e percebi meu erro: eu supus que o jar da Stone estivesse nos repositórios maven. Eu coloquei o fat.jar do 10 e funcionou.
